// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using PelSoftLabTask.entities;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace PelSoftLabTask.entities
{
    public partial interface IPelSoftLabDbContextProcedures
    {
        Task<List<SearchProductsResult>> SearchProductsAsync(string ProductName, string Size, decimal? Price, DateTime? MfgDate, string Category, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SearchProductsWithORResult>> SearchProductsWithORAsync(string ProductName, string Size, decimal? Price, DateTime? MfgDate, string Category, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
