// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PelSoftLabTask.entities
{
    [Table("Product")]
    public partial class Product
    {
        [Key]
        public int ProductID { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string ProductName { get; set; }
        [StringLength(3)]
        [Unicode(false)]
        public string Size { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal? price { get; set; }
        [Column(TypeName = "date")]
        public DateTime? MfgDate { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Category { get; set; }
    }
}